name: 'Terraform Plan'

on: push
env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  
jobs:
  terraform_plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Navegation to Terraform Directory
      run: cd terraforms
    - name: Checkout
      uses: actions/checkout@v4
    - name: Terraform Plan
      run: |
        terraform init
        terraform validate
        terraform plan




  